#!/bin/bash
# sync-monitors.sh — Auto-detect active monitors, write monitors.conf and waybar config.
# Usage:
#   sync-monitors.sh           — update configs, auto-reload if anything changed
#   sync-monitors.sh --reload  — update configs and always reload sway + restart waybar

set -euo pipefail

MONITORS_CONF="${XDG_CONFIG_HOME:-$HOME/.config}/sway/monitors.conf"
WAYBAR_TMPL="${XDG_CONFIG_HOME:-$HOME/.config}/waybar/config.jsonc.tmpl"
WAYBAR_CONF="${XDG_CONFIG_HOME:-$HOME/.config}/waybar/config.jsonc"
NATIVE="eDP-1"
FORCE_RELOAD="${1:-}"

# --- Gather outputs -------------------------------------------------------

OUTPUTS_JSON=$(swaymsg -t get_outputs)

# Sorted active outputs (left to right by X position), excluding native
mapfile -t SORTED_ALL < <(
    echo "$OUTPUTS_JSON" \
    | jq -r '[.[] | select(.active)] | sort_by(.rect.x)[] | .name'
)

EXTERNALS=()
for name in "${SORTED_ALL[@]}"; do
    [[ "$name" != "$NATIVE" ]] && EXTERNALS+=("$name")
done

MON_LEFT=""
MON_RIGHT=""
[[ ${#EXTERNALS[@]} -ge 1 ]] && MON_LEFT="${EXTERNALS[0]}"
[[ ${#EXTERNALS[@]} -ge 2 ]] && MON_RIGHT="${EXTERNALS[1]}"

# Helper: first available mode (native/highest resolution) for a given output
get_first_mode() {
    echo "$OUTPUTS_JSON" \
    | jq -r --arg n "$1" '.[] | select(.name == $n) | .modes[0] | "\(.width)x\(.height)"'
}

get_width() { echo "$1" | cut -dx -f1; }

# --- Build monitors.conf --------------------------------------------------

NEW_CONF=$(mktemp)
trap 'rm -f "$NEW_CONF"' EXIT

{
    echo "# Auto-generated by sync-monitors.sh — do not edit directly"
    echo ""

    x=0

    if [[ -n "$MON_LEFT" ]]; then
        res=$(get_first_mode "$MON_LEFT")
        w=$(get_width "$res")
        echo "set \$mon_left $MON_LEFT"
        echo "output \$mon_left resolution $res position ${x},0"
        x=$((x + w))
    else
        echo "set \$mon_left __none__"
    fi

    echo ""
    native_res=$(get_first_mode "$NATIVE")
    native_w=$(get_width "$native_res")
    echo "output $NATIVE resolution $native_res position ${x},0"
    x=$((x + native_w))

    if [[ -n "$MON_RIGHT" ]]; then
        res=$(get_first_mode "$MON_RIGHT")
        echo ""
        echo "set \$mon_right $MON_RIGHT"
        echo "output \$mon_right resolution $res position ${x},0"
    else
        echo "set \$mon_right __none__"
    fi
} > "$NEW_CONF"

# --- Update monitors.conf if changed --------------------------------------

CHANGED=false
if ! diff -q "$NEW_CONF" "$MONITORS_CONF" &>/dev/null 2>&1; then
    cp "$NEW_CONF" "$MONITORS_CONF"
    CHANGED=true
    echo "monitors.conf updated:"
else
    echo "monitors.conf unchanged:"
fi

echo "  native    eDP-1"
[[ -n "$MON_LEFT"  ]] && echo "  left      $MON_LEFT"
[[ -n "$MON_RIGHT" ]] && echo "  right     $MON_RIGHT"

# --- Regenerate waybar config from template -------------------------------

if [[ -f "$WAYBAR_TMPL" ]]; then
    LEFT_VAL="${MON_LEFT:-__none__}"
    RIGHT_VAL="${MON_RIGHT:-__none__}"
    sed "s/MON_LEFT/$LEFT_VAL/g; s/MON_RIGHT/$RIGHT_VAL/g" "$WAYBAR_TMPL" > "$WAYBAR_CONF"
    echo "waybar config.jsonc regenerated (left=$LEFT_VAL right=$RIGHT_VAL)"
fi

# --- Reload if needed -----------------------------------------------------

if [[ "$CHANGED" == true || "$FORCE_RELOAD" == "--reload" ]]; then
    swaymsg reload
    pkill waybar 2>/dev/null || true
    sleep 0.3
    waybar &>/dev/null &
    echo "sway reloaded, waybar restarted"
fi
