[colors]
draw_bold_text_with_bright_colors = true

# Colors (Iris)

# Default colors
[colors.primary]
background = '#272537'
foreground = '#e8e6e9'

# Normal colors
[colors.normal]
black   = '#111133'
red     = '#d61d52'
green   = '#48a842'
yellow  = '#e1a51c'
blue    = '#5556d3'
magenta = '#8650d3'
cyan    = '#52afb7'
white   = '#9f9aa7'

# Bright colors
[colors.bright]
black   = '#484867'
red     = '#e15877'
green   = '#71ab3a'
yellow  = '#c6a642'
blue    = '#6d6dc9'
magenta = '#956ad3'
cyan    = '#6ab6bd'
white   = '#e8e6e9'

[font]
size = 12.0

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Alt"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mode = "~Search"
mods = "Alt"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = true
